name: ci
on: [push]

jobs:
  run:
    name: Spell  check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check resume.md spelling
        uses: crate-ci/typos@v1.13.26
        with:
          files: ./resume.md
