name: ci
on: [push]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check resume.md spelling
        uses: crate-ci/typos@v1.13.26
        with:
          files: ./resume.md

  build:
    needs: spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest resumerk
        run: |
          gh release download --repo braheezy-resume/resumerk --pattern '*linux*'
          tar xf *.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert resume
        run: ./resumerk resume.md

      - uses: actions/upload-artifact@v3
        with:
          name: resume_files
          path: |
            resume.html
            resume.pdf
            resume.md

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: resume_files

      - name: Deploy all artifacts to Github
        uses: softprops/action-gh-release@v1
        with:
          files: resume.*

      - name: Deploy HTML to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: resume.html
